<script type="text/javascript" src="include/js/jquery-2.2.2.min.js"></script> 
<script type="text/javascript" src="include/js/bootstrap.min.js"></script> 
<script type="text/javascript" src="include/js/animsition.min.js"></script> 
<script type="text/javascript" src="include/js/jquery.validate.js"></script>
<script type="text/javascript" src="include/js/classie.js"></script> 
<script type="text/javascript" src="include/js/main.js"></script> 
<script type="text/javascript" src="include/js/waypoint.js"></script> 
<script type="text/javascript" src="include/js/slick.min.js"></script> 
<script type="text/javascript" src="include/js/jquery.countTo.js"></script> 
<script type="text/javascript" src="include/js/imagesloaded.js"></script> 
<script type="text/javascript" src="include/js/masonry-3.1.4.js"></script> 
<script type="text/javascript" src="include/js/masonry.filter.js"></script> 
<script type="text/javascript" src="include/js/jquery.magnific-popup.min.js"></script> 
<script type="text/javascript" src="include/js/jquery.vide.js"></script>
<script type="text/javascript" src="include/js/simple.parallax.js"></script>
<script type="text/javascript" src="include/js/custom.js"></script>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-576b8f979487378e"></script>